config/routes.rb
Rails.application.routes.draw do
  resources :links
  get '/link_update/:id', to: 'links#update_info', as: 'link_update'
  
  root 'welcome#index'
  
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :link
end

app/models/link.rb
class Link < ActiveRecord::Base
    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy, :update_info]
  
  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)
    object = MetaInspector.new(@link.url)
    @link.description = object.best_description
    @link.title = object.best_title
    @link.img = object.images.best
    

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update_info
    object = MetaInspector.new(@link.url)
    @link.description = object.best_description
    @link.title = object.best_title
    @link.img = object.images.best
    @link.save
    redirect_to links_url, notice: 'Link was successfully updated.'
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :description, :url, :img)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    
    
    def index
        @object = Link.paginate(:page => params[:page], :per_page => 4)
        @link = Link.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Links - The LinkManager WebApp</title>

  <!-- CSS  -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/css/materialize.min.css">
  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/js/materialize.min.js"></script>
  <%= csrf_meta_tags %>

  
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
  
  
</head>
<body>
  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><%= link_to "Links", root_path, id: "logo-container", class: "brand-logo" %>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to 'Admin', links_path %></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="#">Admin</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  

  <div class="container-fluid">
    <div class="section">

     <%= yield %>

    </div>
    <br><br>
  </div>

  <footer class="page-footer blue">
    <div class="container-fluid">
      <div class="row">
        <div class="col l10 s12 offset-l2">
          <h6 class="white-text">Qui suis-je ?</h6>
          <p class="grey-text text-lighten-4">Xennial, je suis un geek qui s'amuse avec le code (ruby on rails) pour me simplifier la vie au quotidien.</p>


        </div>
        <!-- à voir plus tard -->
        <div class="col l3 s12">
          <!--<h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
          </ul>-->
        </div>
        <div class="col l3 s12">
          <!--<h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
          </ul>-->
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made with <i class="material-icons">favorite</i> using <a href="https://materializecss.com/" class="grey-text text-lighten-4">Materialize CSS</a>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/links/_form.html.erb
<div class="container">
  <%= form_for(@link) do |f| %>
    <% if @link.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>
    
        <ul>
        <% @link.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
      <div class="row">
         <div class="input-field col s3">
          <%= image_tag @link.img, style: "max-width:150px" %>
        </div>
        <div class="input-field col s5">
          <%= f.text_field :title, id: "title", class: "validate" %>
        </div>
        <div class="input-field col s5">
          <%= f.text_field :description, id: "desc", class: "validate" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <%= f.text_field :url, id: "url", class: "validate" %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <%= f.text_field :img, id: "image", class: "validate" %>
        </div>
      </div>
    
    <div class="actions">
      <%= f.submit "Valider", class: "waves-effect waves-light btn" %>
    </div>
  <% end %>

</div>

app/views/links/edit.html.erb
<div class="container">
    <%= render 'form' %>
</div>

app/views/links/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  
  <table class="highlight responsive">
    <thead>
      <tr>
        <th>Titre</th>
        <th>Description</th>
        <th>Catégorie</th>
        <th colspan="4"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @links.each do |link| %>
        <tr>
          <td><%= link.url %></td>
          <td><%= link.updated_at.strftime("Ajouté le %d/%m/%Y à %Hh%M") %></td>
          <td>
            <% if link.category.nil? %>
              <%= link_to 'Ajouter une catégorie', root_path %>
            <% else %>
              <%= link.category.name %>
            <% end %>
          </td>
          <td><%= link_to link_update_path(link) do %><i class="small material-icons">autorenew</i><% end %></td>
          <td><%= link_to 'Voir', link, class: "btn waves-effect waves-light" %></td>
          <td><%= link_to 'Editer', edit_link_path(link), class: "btn waves-effect waves-light blue" %></td>
          <td><%= link_to 'Supprimer', link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn waves-effect waves-light red" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
</div>

app/views/links/new.html.erb
<div class="container">
    <nav>
        <div class="nav-wrapper">
          <div class="col s12">
            <%= link_to "Links", root_path, class: "breadcrumb" %>
            <a href="#!" class="breadcrumb">Nouveau Lien</a>
          </div>
        </div>
    </nav>
</div>
<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<div class="container">
  <% if !notice.nil? %>
    <div id="card-alert" class="card green lighten-5">
      <div class="card-content green-text">
        <p id="notice"><%= notice %></p>
      </div>
    </div>
  <% end %>
  <nav>
    <div class="nav-wrapper blue darken-4">
      <div class="col s10">
        <a href="/" class="breadcrumb">Home</a>
          <% if @link.category.nil? %>
            Pas de catégorie
          <% else %>
            <%= link_to 'Ajouter une catégorie', root_path, class: "breadcrumb" %>
          <% end %>
        </a>
        <a href="/" class="breadcrumb"><%= @link.title %></a>
      </div>
    </div>
  </nav>
  <div class="row">
    <div class="col s12 m6 offset-m3">
      <div class="card hoverable">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="<%= @link.img %>">
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= @link.title %><i class="material-icons right">more_vert</i></span>
          <p><%= link_to @link.url %></p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= @link.title %><i class="material-icons right">close</i></span>
          <p><%= @link.description %></p>
        </div>
      </div>
    </div>
    <div class="col s12 m6 offset-m3 center">
      <%= link_to 'Editer le lien, il manque des infos', edit_link_path(@link), class: "waves-effect waves-light btn red" %> 
      <%= link_to 'Le lien est OK pour moi', root_path, class: "waves-effect waves-light btn blue" %>    
    </div>
  </div>
  
</div>

app/views/welcome/_form.html.erb
<%= form_for @link do |l| %>
    <div class="row">
        <div class="input-field col s5 offset-s2">
            <%= l.text_field :url, placeholder: "http://www.exemple.com", id: "title", class: "validate" %>
            <label class="active" for="title">Adresse du site</label>
        </div>
        <br>
        <%= l.submit "Ajouter", class: "waves-effect waves-light btn" %>
    </div>
<% end %>

app/views/welcome/index.html.erb
<div class="container-fluid">
  <!-- Rendu du formulaire d'ajout -->
  <%= render 'form' %>

  <div class="row">
   <ul id="slide-out" class="side-nav">
    <li><div class="user-view">
        <div class="background">
          <img src="http://materializecss.com/images/office.jpg">
        </div>
        <a href="#!user"><img class="circle" src="http://materializecss.com/images/yuna.jpg"></a>
        <a href="#!name"><span class="white-text name">John Doe</span></a>
        <a href="#!email"><span class="white-text email">jdandturk@gmail.com</span></a>
        </div>
      </li>
      <li><a href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
      <li><a href="#!">Second Link</a></li>
      <li><div class="divider"></div></li>
      <li><a class="subheader">Subheader</a></li>
      <li><a class="waves-effect" href="#!">Third Link With Waves</a></li>
    </ul>
    <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i>MENU</a>
  
  <script>
  // Initialize collapse button
  $(".button-collapse").sideNav();
  // Initialize collapsible (uncomment the line below if you use the dropdown variation)
  //$('.collapsible').collapsible();  
  </script>
  
  
    <div class="col m2 hide-on-small-only">
      <ul class="collapsible collapsible-accordion">
          <li class="bold">
            <a class="collapsible-header waves-effect waves-cyan"><i class="material-icons">grade</i> Layouts</a>
            <div class="collapsible-body">
              <ul>
                <li><a href="layout-fullscreen.html">Full Screen</a></li>
                <li><a href="layout-horizontal-menu.html">Horizontal Menu</a></li>
              </ul>
            </div>
          </li>
      </ul>  
    
        <ul class="collection">
          <li class="collection-item avatar">
            <img src="https://materializecss.com/images/yuna.jpg" alt="" class="circle">
            <span class="title">Mieux notés</span>
            <p>Les sites les mieux notés</p>
            <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
          </li>
          <li class="collection-item avatar">
            <i class="material-icons circle">folder</i>
            <span class="title">Liens morts</span>
            <p>Sites qui ne fonctionnent plus</p>
            <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
          </li>
          <li class="collection-item avatar">
            <i class="material-icons circle">folder</i>
            <span class="title">Non catégorisé</span>
            <p>Sites sans catégorie</p>
            <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
          </li>
          <li class="collection-item avatar">
            <i class="material-icons circle">folder</i>
            <span class="title">Catégorie 1</span>
            <p>Sites de la Catégorie 1</p>
            <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
          </li>
        </ul>
    </div>

    <div class="col s12 m10">
      <!-- Teal page content  -->
    
      <% @object.each do |obj| %>
        <!-- Carte -->
        <div class="col s12 m5">
          <div class="card horizontal hoverable">
            <div class="card-image">
              <img src="<%= obj.img %>" class="responsive-img" style="max-width:150px">
            </div>
            <div class="card-stacked">
              <div class="card-content">
                <p class="card-title"><%= obj.title %></p>
                <p><%= obj.description %></p>
              </div>
              <div class="card-action">
                <%= link_to 'Visiter', obj.url %><span class="new badge" data-badge-caption="Nouveau"><%= obj.visit_nb %></span>
                <%= link_to 'Editer', edit_link_path(obj) %>
                <%= obj.created_at.strftime("Ajouté le %d/%m/%Y à %Hh%M") %>
              </div>
            </div>
          </div>
        </div>
        <!-- fin de la carte -->
      <% end %>
    </div>
    
  </div>
  <div class="pagination center">
    <div class="page_info">
      <%= page_entries_info @object %>
    </div>
    <%= will_paginate @object %>
  </div>

  
</div>